version: '3.3'

services:
  node: 
    build:
      context:  ./docker/environments/dev/node
    volumes:
      - ./:/app
    container_name: ${POJECT}_node
    command: tail -f /dev/null
    hostname: ${PROJECT_PREFIX}-node
    working_dir: /app/code
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=postgres
      - SONAR_HOST_URL=http://sonarqube:9000
      - SONAR_LOGIN=${SONAR_LOGIN}
      - SONAR_PASSWORD=${SONAR_PASSWORD}
      - SONAR_PROJECT_TOKEN=${SONAR_PROJECT_TOKEN}
      - SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}
    ports:
      - ${APP_PORT}:3000

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  
  postgres:
    image: postgres:13
    container_name: ${POJECT}_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_TEST=${DB_NAME}_test
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/environments/dev/postgre/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh


  pgadmin:
    image: dpage/pgadmin4
    container_name: ${POJECT}_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog
    container_name: ${POJECT}_mailhog
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_HTTP_PORT}:8025"

volumes:
  postgres_data:
  pgadmin_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: