#!/bin/bash
set -e

 sonar-scanner \
  -Dsonar.projectKey=$SONAR_PROJECT_KEY \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://sonarqube:9000 \
  -Dsonar.token=$SONAR_PROJECT_KEY \
  -Dsonar.javascript.lcov.reportPaths=tests/coverage/e2e/lcov.info \
  -Dsonar.coverage.exclusions=**/tests/**,**/db/migrations/**,**/db/seeders/**
