name: CI

on: 
  push:
    branches:
      - master
  
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.0.0-v8-canary'
      - name: Install dependencies
        run: cd code && cp .env.ci.example .env && npm install && npm run lint

  test-e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: my_store_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pa5swod
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.0.0-v8-canary'
      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for postgres...";
            sleep 2;
          done
      - name: Setup
        run: cd code && cp .env.ci.example .env && npm install 
      - name: Migrations
        run: cd code && npm run migrations:run
      - name: Run E2E 
        run: cd code && npm run e2e:ci
      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: code/tests/coverage/e2e/lcov.info

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [test-e2e]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: code/tests/coverage/e2e
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jfcodiaz
            -Dsonar.projectKey=jfcodiaz_my-store
            -Dsonar.javascript.lcov.reportPaths=code/tests/coverage/e2e/lcov.info